<!DOCTYPE html>


<html>
    <head>
        <?= $this->headTitle(); ?>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php if (count($this->listStudents) != 0): ?>
            <table border='1' >
                <thead>
                    <tr>
                        <th>Mã sinh viên</th><th>Họ và tên</th><th>Ngày sinh</th><th>Giới tính</th><th>Số điện thoại</th><th>Địa chỉ</th><th colspan="2">Tác vụ</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->listStudents as $student):
//                        $studentId = $student->getStudentId();
//                        $studentName = $student->getStudentName();
//                        $studentDateOfBirth = $student->getDateOfBirth();
//                        $studentGender = ($student->getGender() == 1) ? 'nam' : 'nữ';
//                        $studentPhone = $student->getPhone();
//                        $studentAddress = $student->getAddress();
//                        $deleteUrl = $this->url([
//                            "action" => "delete",
//                            "id" => $studentId
//                        ]);
//                        $editUrl = $this->url([
//                            "action" => "edit",
//                            "id" => $studentId
//                        ]);
                        $studentId = $this->escape($student->studentId);
                        $studentName = $this->escape($student->studentName);
                        $studentDateOfBirth = $this->escape($student->dateOfBirth);
                        $studentGender = ($student->gender == 1) ? 'nam' : 'nữ';
                        $studentPhone = $this->escape($student->phone);
                        $studentAddress = $this->escape($student->address);
                        $deleteUrl = $this->url([
                            "action" => "delete",
                            "id" => $studentId
                        ]);
                        $editUrl = $this->url([
                            "action" => "edit",
                            "id" => $studentId
                        ]);
                        ?>
                        <tr>
                            <td><?= $studentId ?></td>
                            <td><?= $studentName ?></td>
                            <td><?= $studentDateOfBirth ?></td>
                            <td><?= $studentGender ?></td>
                            <td><?= $studentPhone ?></td>
                            <td><?= $studentAddress ?></td>
                            <td><a href="<?= $deleteUrl ?>">Xóa</a></td>
                            <td><a href="<?= $editUrl ?>">Sửa</a></td>
                        </tr>
                    <?php endforeach; ?>
            </table>
            <section id="paginator">
                <?= $this->paginationControl($this->listStudents, 'Sliding', '/profile/paginator.phtml'); ?>
            </section>
        <?php else: ?>
            Empty list student
        <?php endif; ?>

    </body>
</html>
