<!DOCTYPE html>


<html>
    <head>
        <title>Profile</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="jumbotron">
            <div class="row">
                <div class="col-xs-6 col-md-2 col-md-offset-2">
                    <a href="#" style="height: 200px" class="thumbnail">
                        <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT-fxRi-wrR7muP_naLzdF4svQVoSDib-lXawGZ1MeEqXCOk487VA" alt="avata">
                    </a>
                    <button type="button" class="btn btn-success center-block">Follow me</button>
                </div>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading text-center"><h4>Profile</h4></div>
                        <div class="panel-body">

                            <dl class="dl-horizontal h4">
                                <dt>MSSV</dt>
                                <dd>1222222</dd>
                                <dt>Name</dt>
                                <dd>Ngo Duc Hai</dd>
                                <dt>Date of birthday</dt>
                                <dd>06/03/1994</dd>
                                <dt>Gender</dt>
                                <dd>Nam</dd>
                                <dt>Phone</dt>
                                <dd>01659338885</dd>
                                <dt>Address</dt>
                                <dd>Tan Yen - Bac Giang</dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
