<?php if ($this->pageCount > 1): ?>
    <div class="paginationControl" align="center">
        <?php
        if($this->current==$this->first){
            
            echo "first | prev ";
        }else{
            echo '<a href="' . $this->url(array('page' => 1)) . '">first</a>';
            echo '<a href="' . $this->url(array('page' => $this->previous)) . '"> |prev</a> | ';
        }
        foreach ($this->pagesInRange as $page) {
            if ($page != $this->current) {
                echo '<a href="' . $this->url(array('page' => $page)) . '">' . $page . '</a> | ';
            } else {
                echo $page . ' | ';
            }
        }
        if($this->current==$this->last){
            
            echo "next | last";
        }else{
            echo '<a href="' . $this->url(array('page' => $this->next)) . '"> next | </a>';
            echo '<a href="' . $this->url(array('page' => $this->last)) . '"> last</a>';
        }
            ?>
    </div>
<?php endif; ?>