<?php

/* @var $this Zend_View */

echo $this->doctype();
echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
$this->headLink()->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css');
$this->headLink()->appendStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css');
echo $this->headLink();

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.11.3.min.js');
$this->headScript()->appendFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js');
echo $this->headScript();
echo $this->layout()->content;
